#!/bin/bash
killall picom
[ $(xrandr | grep -sw 'connected' | wc -l) = 1 ] && [ $(xrandr | grep -sw '5120x1440' | wc -l) = 1 ] && xrandr --output DP-0 --off --output DP-1 --off --output HDMI-0 --off --output DP-2 --mode 5120x1440 --pos 0x0 --rotate normal --output   DP-3 --off --output DP-4 --off --output DP-5 --off --output USB-C-0 --off
[ $(xrandr | grep -sw 'connected' | wc -l) = 1 ] && [ $(xrandr | grep -sw 'DP-2 Connected 3840x1080' | wc -l) = 1 ] && xrandr --output DP-0 --off --output DP-1 --off --output HDMI-0 --off --output DP-2 --mode 2560x1440 --pos 0x0 --rotate normal --output     DP-3 --off --output DP-4 --off --output DP-5 --off --output USB-C-0 --off
[ $(xrandr | grep -sw 'connected' | wc -l) = 1 ] && [ $(xrandr | grep -sw 'DP-4 Connected 3840x1080' | wc -l) = 1 ] && xrandr --output DP-0 --off --output DP-1 --off --output HDMI-0 --off --output DP-2 --off --rotate normal --output     DP-3 --off --output DP-4 --mode 2560x1440 --pos 0x0 --rotate normal --output DP-5 --off --output USB-C-0 --off
[ $(xrandr | grep -sw 'connected' | wc -l) = 2 ] && xrandr --output DP-0 --off --output DP-1 --off --output HDMI-0 --off --output DP-2 --mode 2560x1440 --pos 0x0 --rotate normal --output  DP-3 --off --output DP-4 --mode 2560x1440 --pos 2560x0 --rotate normal --output DP-5 --off --output USB-C-0 --off
[ $(xrandr | grep -sw 'connected' | wc -l) = 3 ] && xrandr --output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate normal  --output DP-2 --mode 2560x1440 --pos 1920x0 --rotate normal --output DP-4 --mode 2560x1440 --pos 4480x0 --rotate normal  --output DP-0 --off --output DP-1 --off --output  DP-3 --off --output DP-5 --off --output USB-C-0 --off
[ $(xrandr | grep -sw 'connected' | wc -l) = 1 ] && [ $(xrandr | grep -sw 'HDMI-0 connected' | wc -l) = 1 ] && xrandr --output DP-0 --off --output DP-1 --off --output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate normal  --output DP-2 --off --output   DP-3 --off --output DP-4 --off --output DP-5 --off --output USB-C-0 --off
[ $(xrandr | grep -sw 'connected' | wc -l) = 1 ] && [ $(xrandr | grep -sw '5120x1440' | wc -l) > 1 ] && feh --bg-fill /home/w/Documents/Wallpapers/wallpapers5120/aus5120scene2.jpg
[ $(xrandr | grep -sw 'connected' | wc -l) = 1 ] && [ $(xrandr | grep -sw 'connected 2560x1440' | wc -l) = 1 ] && feh --bg-fill /home/w/Documents/Wallpapers/wallpapers2560/Hallstatt_Town_Day_2020_2560x1440.jpg
[ $(xrandr | grep -sw 'connected' | wc -l) = 2 ] && feh --bg-center /home/w/Documents/Wallpapers/wallpapers2560/austria-salzburg-city_2560x1440.jpg /home/w/Documents/Wallpapers/wallpapers2560/ws_Hallstatt_Austria_2560x1440.jpg
[ $(xrandr | grep -sw 'connected' | wc -l) = 3 ] && feh --bg-center /home/w/Documents/Wallpapers/wallpapers1920/Aus-Nature1920.jpg /home/w/Documents/Wallpapers/wallpapers2560/austria-salzburg-city_2560x1440.jpg /home/w/Documents/Wallpapers/wallpapers2560/ws_Hallstatt_Austria_2560x1440.jpg
[ $(xrandr | grep -sw 'connected' | wc -l) = 1 ] && [ $(xrandr | grep -sw 'HDMI-0 connected' | wc -l) = 1 ] && feh --bg-center /home/w/Documents/Wallpapers/wallpapers1920/Aus-Nature1920.jpg
picom
