#! /bin/sh
#  ____ _____ 
# |  _ \_   _|  Derek Taylor (DistroTube)
# | | | || |  	http://www.youtube.com/c/DistroTube
# | |_| || |  	http://www.gitlab.com/dwt1/ 
# |____/ |_|  	
#        
# A customized bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

#### AUTOSTART ####
killall picom
$HOME/.config/scripts/mon-set1.sh 
sxhkd &
ntfd &
$HOME/.config/scripts/wall-set.sh &
picom &
$HOME/.config/polybar/launch.sh


#### MONITORS ####
bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DP-4 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    8
bspc config top_padding                   18
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-2)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-4)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-0)

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium state=foating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating follow=on
bspc rule -a timeshift state=floating
bspc rule -a grub-customizer state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a URxvt:urxvt_keys_help state=floating
# bspc rule -a pia_client floating=on
# bspc rule -a qcalc-gtk floating=on follow=on state=floating
